# Generated by Django 5.1.4 on 2025-01-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.URLField(default='timezone.now', max_length=2080),
            preserve_default=False,
        ),
    ]
