# Generated by Django 5.1.4 on 2025-01-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menuitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='carousel_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('tea', 'Tea'), ('pastries', 'Pastries'), ('sandwich', 'Sandwich'), ('ice cream', 'Ice Cream')], max_length=20),
        ),
    ]
