# Generated by Django 5.1.4 on 2025-01-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_carouselitem_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.URLField(max_length=2080),
        ),
    ]
