# Generated by Django 5.1.4 on 2025-01-20 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_alter_carouselitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('tea', 'Tea'), ('pastries', 'Pastries'), ('sandwich', 'Sandwich')], max_length=20),
        ),
    ]
