# Generated by Django 5.1.4 on 2025-01-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'verbose_name': 'Carousel Item', 'verbose_name_plural': 'Carousel Items'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('tea', 'Tea'), ('pastries', 'Pastries'), ('sandwich', 'Sandwich')], max_length=10),
        ),
    ]
