# Generated by Django 5.1.4 on 2025-01-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_carouselitem_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Coffee'), ('tea', 'Tea'), ('juices', 'Juices'), ('pastries', 'Pastries'), ('sandwich', 'Sandwich')], max_length=10),
        ),
    ]
