# Generated by Django 5.1.4 on 2025-01-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_alter_carouselitem_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.URLField(default='timezone.now', max_length=2080),
            preserve_default=False,
        ),
    ]
